blog/urls.py
from django.urls import path

from blog import views

urlpatterns = [
    path('blogs/', views.BlogPostListView.as_view(), name='blog_post_list'),  # For general list
    path('blogs/category/<int:pk>/', views.BlogPostListView.as_view(), name='category_filter'),
    path('single/<int:pk>/', views.SingleTemplateView.as_view(), name='blog-detail'),

]

root/urls.py
from root import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('courses.urls')),
    path('', include('teachers.urls')),
    path('auth/', include('social_django.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

teachers/urls.py
from django.urls import path

from teachers import views

urlpatterns = [
    path('teachers/', views.TeacherListView.as_view(), name='teachers'),
    path('teachers/<int:pk>/', views.TeacherDetailView.as_view(), name='teacher_detail'),

]

teachers/models.py
from django.db import models

from django.db import models


class Teacher(models.Model):
    class LevelChoices(models.TextChoices):
        JUNIOR = 'Junior'
        MIDDLE = 'Middle'
        SENIOR = 'Senior'

    full_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=150, null=True, blank=True)
    rating = models.IntegerField(default=0, null=True, blank=True)
    specialization = models.ForeignKey('courses.Category', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='courses/', null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    level = models.CharField(choices=LevelChoices, default=LevelChoices.MIDDLE.value)

    def __str__(self):
        return self.full_name

teachers/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView

from courses.models import Category
# Create your views here.
from teachers.models import Teacher


class TeacherListView(TemplateView):
    template_name = 'teachers/teacher.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['teachers'] = Teacher.objects.all()
        return context


class TeacherDetailView(TemplateView):
    template_name = 'teachers/teachers-detail.html'

    def get_context_data(self, **kwargs):
        teacher = Teacher.objects.get(pk=self.kwargs['pk'])
        context = super().get_context_data(**kwargs)
        context['teacher'] = teacher
        return context

teachers/templates/teachers/teacher.html
{% extends 'courses/base.html' %}
{% load static %}
{% block content %}

    <!-- Page Header -->
    <div class="container-fluid page-header" style="margin-bottom: 90px;">
        <div class="container">
            <div class="d-flex flex-column justify-content-center" style="min-height: 300px;">
                <h3 class="display-4 text-white text-uppercase">Teachers</h3>
                <div class="d-inline-flex text-white">
                    <p class="m-0 text-uppercase"><a class="text-white" href="/">Home</a></p>
                    <i class="fa fa-angle-double-right pt-1 px-3"></i>
                    <p class="m-0 text-uppercase">Teachers</p>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->

    <!-- Team Start -->
    <div class="container-fluid py-5">
        <div class="container pt-5 pb-3">
            <div class="text-center mb-5">
                <h5 class="text-primary text-uppercase mb-3" style="letter-spacing: 5px;">Teachers</h5>
                <h1>OUR TEACHERS</h1>
            </div>
            <div class="row">
                {% for teacher in teachers %}
                    <div class="col-md-6 col-lg-3 text-center team mb-4">
                        <div class="team-item rounded overflow-hidden mb-2">
                            <div class="team-img position-relative">
                                <!-- Display Image -->
                                <div class="team-img position-relative">
                                    <!-- Display Image -->
                                    <img class="img-fluid" src="{{ teacher.image.url }}" alt="{{ teacher.full_name }}">
                                    <!-- Debugging line to check the image URL -->

                                </div>
                                <a class="btn btn-outline-light btn-square mx-1" href="#" aria-label="Twitter">
                                    <i class="fab fa-twitter"></i>
                                </a>
                                <a class="btn btn-outline-light btn-square mx-1" href="#" aria-label="Facebook">
                                    <i class="fab fa-facebook-f"></i>
                                </a>
                                <a class="btn btn-outline-light btn-square mx-1" href="#" aria-label="LinkedIn">
                                    <i class="fab fa-linkedin-in"></i>
                                </a>
                            </div>
                        </div>
                        <div class="bg-secondary p-4">
                            <!-- Link the Name -->
                            <h5><a href="{% url 'teacher_detail' teacher.id %}">{{ teacher.full_name }}</a></h5>
                            <p class="m-0">{{ teacher.specialization }}</p>
                        </div>
                    </div>
                    </div>
                {% endfor %}
        </div>

    </div>
    </div>
    <!-- Team End -->

{% endblock %}

teachers/templates/teachers/teachers-detail.html
{% extends 'courses/base.html' %}
{% load static %}

{% block title %}{{ teacher.full_name }} - Teacher Profile{% endblock %}

{% block content %}
<div class="container py-5">
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <img src="{{ teacher.image.url }}" class="card-img-top" alt="{{ teacher.full_name }}">
                <div class="card-body text-center">
                    <h5 class="card-title">{{ teacher.full_name }}</h5>
                    <p class="card-text"><strong>Specialization:</strong> {{ teacher.specialization }}</p>
                    <p class="card-text"><strong>Level:</strong> {{ teacher.get_level_display }}</p>
                    <p class="card-text"><strong>Rating:</strong> {{ teacher.rating }}</p>
                    <a href="mailto:{{ teacher.email }}" class="btn btn-primary btn-block">Contact</a>
                    <div class="mt-3">
                        <a class="btn btn-outline-secondary btn-square mx-1" href="#" aria-label="Twitter">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a class="btn btn-outline-secondary btn-square mx-1" href="#" aria-label="Facebook">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a class="btn btn-outline-secondary btn-square mx-1" href="#" aria-label="LinkedIn">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">About {{ teacher.full_name }}</h4>
                    <p class="card-text">{{ teacher.description }}</p>

              
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}