blog/urls.py
from django.urls import path

from blog import views

urlpatterns = [
    path('blogs/', views.BlogPostListView.as_view(), name='blog_post_list'),  # For general list
    path('blogs/category/<int:pk>/', views.BlogPostListView.as_view(), name='category_filter'),
    path('single/<int:pk>/', views.SingleTemplateView.as_view(), name='blog-detail'),

]

root/urls.py
from root import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('courses.urls')),
    path('', include('teachers.urls')),
    path('auth/', include('social_django.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models


class Author(models.Model):
    full_name = models.CharField(max_length=150)
    education = models.CharField(max_length=300, null=True, blank=True)
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.full_name


class Blog(models.Model):
    title = models.CharField(max_length=120)
    content = models.TextField()
    date_added = models.DateField(auto_now_add=True)
    auther_id = models.ManyToManyField(Author, blank=True)
    category = models.ForeignKey('courses.Category', blank=True, on_delete=models.CASCADE, related_name='blogs')

    def __str__(self):
        return self.title


class BlogImage(models.Model):
    image = models.ImageField(upload_to='images/')
    blog_id = models.ForeignKey(Blog, on_delete=models.CASCADE)


class BlogComment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(null=True, blank=True)
    comment = models.TextField()
    date_added = models.DateField(auto_now_add=True)
    is_published = models.BooleanField(default=False)
    blog_id = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')

    def __str__(self):
        return self.name

blog/forms.py
from django import forms

from blog.models import BlogComment


class BlogCommentForm(forms.ModelForm):
    class Meta:
        model = BlogComment
        fields = ['name', 'email', 'comment']

blog/views.py
from django.http import request
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from django.views.generic import ListView, TemplateView, View, FormView

from blog.forms import BlogCommentForm
from blog.models import Blog, Author
from courses.models import Course, Category


# Create your views here.
class BlogPostListView(TemplateView):
    template_name = 'blog/blog.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        blogs = Blog.objects.all()
        categories = Category.objects.all()

        # Handle category filtering
        category_id = self.kwargs.get('pk')
        if category_id:
            category = get_object_or_404(Category, pk=category_id)
            blogs = blogs.filter(
                category=category)  # Assuming your Blog model has a ManyToManyField named 'categories'
        authors = Author.objects.all()

        context['categories'] = categories
        context['blogs'] = blogs
        context['authors'] = authors
        return context


class SingleTemplateView(TemplateView):
    template_name = 'blog/single.html'

    def get_context_data(self, **kwargs):
        blogs = Blog.objects.all()
        categories = Category.objects.all()
        blog = Blog.objects.get(pk=self.kwargs['pk'])
        comments = blog.comments.all()
        authors = blog.auther_id.all()
        context = super().get_context_data(**kwargs)
        context['blog'] = blog
        context['authors'] = authors
        context['categories'] = categories
        context['blogs'] = blogs
        context['comments'] = comments
        return context

    def post(self, request, *args, **kwargs):
        blog = get_object_or_404(Blog, pk=self.kwargs['pk'])
        form = BlogCommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.is_published = True
            comment.blog_id = blog
            comment.save()
            return redirect(reverse('blog-detail', kwargs={'pk': blog.pk}))
        # If the form is not valid, re-render the context with the form errors
        context = self.get_context_data(**kwargs)
        context['form'] = form
        return self.render_to_response(context)

blog/templates/blog/blog.html
{% extends 'courses/base.html' %}
{% load static %}
{% block content %}



    <!-- Blog Start -->
    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="row">
                <div class="col-lg-8">
                    <div class="row pb-3">
                        <div class="row">
                            {% for blog in blogs %}
                                <div class="col-lg-6 mb-4">
                                    <div class="blog-item position-relative overflow-hidden rounded mb-2">
                                        <img class="img-fluid" src="{{ blog.blogimage_set.first.image.url }}" alt="">
                                        <a class="blog-overlay text-decoration-none"
                                           href="{% url 'blog-detail' blog.id %}">
                                            <h5 class="text-white mb-3">{{ blog.title }}</h5>
                                            <p class="text-primary m-0">{{ blog.date_added }}</p>
                                            <!-- Use the actual date from the blog -->
                                        </a>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>


                        <div class="col-12">
                            <nav aria-label="Page navigation">
                                <ul class="pagination pagination-lg justify-content-center mb-0">
                                    <li class="page-item disabled">
                                        <a class="page-link" href="#" aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                            <span class="sr-only">Previous</span>
                                        </a>
                                    </li>
                                    <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                                    <li class="page-item">
                                        <a class="page-link" href="#" aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                            <span class="sr-only">Next</span>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4 mt-5 mt-lg-0">
{#                    <!-- Author Bio -->#}
{#                    <div class="d-flex flex-column text-center bg-dark rounded mb-5 py-5 px-4">#}
{#                        <img src="{{ authors.first.image.url }}" class="img-fluid rounded-circle mx-auto mb-3"#}
{#                             style="width: 100px;">#}
{#                        <h3 class="text-primary mb-3">{{ authors.first }}</h3>#}
{#                        <h3 class="text-uppercase mb-4" style="letter-spacing: 5px;">Tag Cloud</h3>#}
{#                        <p class="text-white m-0">{{ authors.first.education }}</p>#}
{#                    </div>#}
{##}
{#                    <!-- Search Form -->#}
{#                    <div class="mb-5">#}
{#                        <form action="">#}
{#                            <div class="input-group">#}
{#                                <input type="text" class="form-control form-control-lg" placeholder="Keyword">#}
{#                                <div class="input-group-append">#}
{#                                    <span class="input-group-text bg-transparent text-primary"><i#}
{#                                            class="fa fa-search"></i></span>#}
{#                                </div>#}
{#                            </div>#}
{#                        </form>#}
{#                    </div>#}
{##}
{#                    <!-- Category List -->#}
{#                    <div class="mb-5">#}
{#                        <h3 class="text-uppercase mb-4" style="letter-spacing: 5px;">Categories</h3>#}
{#                        <ul class="list-group list-group-flush">#}
{#                            {% for category in categories %}#}
{#                                <li class="list-group-item d-flex justify-content-between align-items-center px-0">#}
{#                                    <a href="{% url 'category_filter' category.pk %}"#}
{#                                       class="text-decoration-none h6 m-0">{{ category.title }}</a>#}
{#                                    <span class="badge badge-primary badge-pill">{{ category.blogs.count}}</span>#}
{#                                </li>#}
{#                            {% endfor %}#}
{#                        </ul>#}
{#                    </div>#}

                    <!-- Recent Post -->
                    <style>
                        .recent-post-img {
                            width: 80px; /* Set the width of the image */
                            height: 80px; /* Set the height of the image */
                            object-fit: cover; /* Ensure the image covers the area without stretching */
                        }
                    </style>

                    <div class="mb-5">
                        <h3 class="text-uppercase mb-4" style="letter-spacing: 5px;">Recent Post</h3>
                        {% for blog in blogs|slice:":3" %}
                            <a class="d-flex align-items-center text-decoration-none mb-3"
                               href="{% url 'blog-detail' blog.id %}">
                                <img class="img-fluid rounded recent-post-img"
                                     src="{{ blog.blogimage_set.first.image.url }}" alt="">
                                <div class="pl-3">
                                    <h6 class="m-1">{{ blog.title }}</h6>
                                    <small>{{ blog.date_added }}</small>
                                </div>
                            </a>
                        {% endfor %}
                    </div>

                    <!-- Tag Cloud -->
                    
                </div>
            </div>
        </div>
    </div>
    <!-- Blog End -->


{% endblock %}

blog/templates/blog/single.html
{% extends 'courses/base.html' %}
{% load static %}
{% block content %}


    <!-- Detail Start -->
    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="row">
                <div class="col-lg-8">
                    <div class="mb-5 blog-container">
                        <!-- Blog Date -->
                        <h6 class="blog-date text-primary mb-3">{{ blog.date_added|date:"F d, Y" }}</h6>

                        <!-- Blog Title -->
                        <h1 class="blog-title mb-5">{{ blog.title }}</h1>

                        <!-- Blog Content -->
                        <p class="blog-content lead">{{ blog.content }}</p>

                        <!-- Inline Images -->
                        <div class="blog-images">
                            {% if blog.blogimage_set.exists %}
                                <img class="img-fluid rounded" src="{{ blog.blogimage_set.last.image.url }}"
                                     alt="{{ blog.title }}" width="300" height="auto">
                                <img class="img-fluid rounded ml-3" src="{{ blog.blogimage_set.first.image.url }}"
                                     alt="Image" width="300" height="auto">
                            {% else %}
                                <img class="img-fluid rounded" src="{% static 'path/to/default/image.jpg' %}"
                                     alt="Default image" width="300" height="auto">
                            {% endif %}
                        </div>
                    </div>


                    <!-- Comment List -->
                    <div class="mb-5">
                        <h3 class="text-uppercase mb-4" style="letter-spacing: 5px;"> Comments</h3>
                        {% for comment in comments %}
                            <div class="media-body">
                                <h6>{{ comment.name  }} <small><i>{{ comment.date_added}}</i></small></h6>
                                <p>{{ comment.comment}}</p>
                                <button class="btn btn-sm btn-secondary">Reply</button>
                            </div>
                        {% endfor %}
                       
                      
                    </div>

                    <!-- Comment Form -->
                    <div class="bg-secondary rounded p-5">
                        <h3 class="text-uppercase mb-4" style="letter-spacing: 5px;">Leave a comment</h3>
                        <form method="post" action="">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name">Name *</label>
                                <input type="text" name="name" class="form-control border-0" id="name">
                            </div>
                            <div class="form-group">
                                <label for="email">Email *</label>
                                <input type="email" name="email" class="form-control border-0" id="email">
                            </div>
                            

                            <div class="form-group">
                                <label for="message">Comment *</label>
                                <textarea id="message" name="comment" cols="30" rows="5" class="form-control border-0"></textarea>
                            </div>
                            <div class="form-group mb-0">
                                <input type="submit" value="Leave Comment"
                                       class="btn btn-primary py-md-2 px-md-4 font-weight-semi-bold">
                            </div>
                        </form>
                    </div>
                </div>

                <div class="col-lg-4 mt-5 mt-lg-0">
                    <!-- Author Bio -->
                    {% for author in authors %}
                        <div class="d-flex flex-column text-center bg-dark rounded mb-5 py-5 px-4">
                            <img src="{{ author.image.url }}" class="img-fluid rounded-circle mx-auto mb-3"
                                 style="width: 100px;">
                            <h3 class="text-primary mb-3">{{ blog.auther_id.first }}</h3>
                            <h3 class="text-uppercase mb-4" style="letter-spacing: 5px;">Tag Cloud</h3>
                            <p class="text-white m-0">{{ author.education }}</p>
                        </div>
                    {% endfor %}

                    <!-- Search Form -->
                    <div class="mb-5">
                        <form action="">
                            <div class="input-group">
                                <input type="text" class="form-control form-control-lg" placeholder="Keyword">
                                <div class="input-group-append">
                                    <span class="input-group-text bg-transparent text-primary"><i
                                            class="fa fa-search"></i></span>
                                </div>
                            </div>
                        </form>
                    </div>
                    <style>
                        .recent-post-img {
                            width: 80px; /* Set the width of the image */
                            height: 80px; /* Set the height of the image */
                            object-fit: cover; /* Ensure the image covers the area without stretching */
                        }
                    </style>
                    <!-- Category List -->
                    <div class="mb-5">
                        <h3 class="text-uppercase mb-4" style="letter-spacing: 5px;">Categories</h3>
                        <ul class="list-group list-group-flush">
                            {% for category in categories %}
                                <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                                    <a href="{% url 'category_filter' category.pk %}"
                                       class="text-decoration-none h6 m-0">{{ category.title }}</a>
                                    <span class="badge badge-primary badge-pill">{{ category.blogs.count }}</span>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>

                    <!-- Recent Post -->
                    <div class="mb-5">
                        <h3 class="text-uppercase mb-4" style="letter-spacing: 5px;">Recent Post</h3>
                        {% for blog in blogs|slice:":3" %}
                            <a class="d-flex align-items-center text-decoration-none mb-3"
                               href="{% url 'blog-detail' blog.id %}">
                                <img class="img-fluid rounded recent-post-img"
                                     src="{{ blog.blogimage_set.first.image.url }}" alt="">
                                <div class="pl-3">
                                    <h6 class="m-1">{{ blog.title }}</h6>
                                    <small>{{ blog.date_added }}</small>
                                </div>
                            </a>
                        {% endfor %}

                    </div>

                    <!-- Tag Cloud -->
                   
                </div>
            </div>
        </div>
    </div>
    <!-- Detail End -->

{% endblock %}